version: 2.1

orbs:
  node: circleci/node@5.0.1
  ruby: circleci/ruby@1.4.1

jobs:
  node_subfolder_test:
    working_directory: ~/example/node
    executor:
      name: node/default
      tag: '17.7'
    steps:
      - checkout:
          path: ~/example
      - node/install-packages:
          include-branch-in-cache-key: false
      - run: npm run test

  ruby_subfolder_test:
    working_directory: ~/example/ruby
    docker:
      - image: 'cimg/ruby:2.7.5'
    steps:
      - checkout:
          path: ~/example
      - ruby/install-deps
      - ruby/rspec-test

  node_test:
    executor:
      name: node/default
      tag: '17.7'
    steps:
      - checkout
      - node/install-packages:
          include-branch-in-cache-key: false
      - run: npm run test

  ruby_test:
    docker:
      - image: 'cimg/ruby:2.7.5'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  test:
    jobs:
      - node_test
      - ruby_test
      - node_subfolder_test
      - ruby_subfolder_test
