version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  node_test:
    executor:
      name: node/default
      tag: '14.14.0'
    steps:
      - checkout
      - node/install-packages
      - run: npm run test

workflows:
  test:
    jobs:
      - node_test
