name: Node.js Example Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.14.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.14.0
    - run: npm run test
